version: "3.9"

services:
  clamav-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clamav-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MAX_FILE_SIZE_MB: 200
    restart: unless-stopped
    volumes:
      - clamav-db:/var/lib/clamav

volumes:
  clamav-db:
