name: .NET Build and Test Template

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
        description: "The name of the project"
      project_path:
        required: true
        type: string
        description: "The relative path to the project directory"
      run_tests:
        required: false
        type: boolean
        default: true
        description: "Flag to run or skip tests"
env:
  DOTNET_VERSION: '10.0.x'
  EF_VERSION: '6.0.5'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project_path }}

    - name: Build
      env:
        CI: true
        PROJECT_PATH: ${{ inputs.project_path }}
      run: dotnet build --no-restore --configuration Release -p:CI="$CI" "$PROJECT_PATH"

    - name: Build Docker Image
      run: docker compose build

    - name: Run Tests
      if: ${{ inputs.run_tests }}
      run: |
        dotnet test src/Arcus.ClamAV.Tests/bin/Release/net10.0/Arcus.ClamAV.Tests.dll \
          --verbosity normal \
          --logger "trx;LogFileName=test-results.trx" \
          --collect:"XPlat Code Coverage"

    - name: Upload Coverage Reports
      if: ${{ inputs.run_tests }}
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Publish Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/test-results.trx'
        check_name: Unit Test Results